### ISSUE TITLE
V2 neo preview script not working 

### ISSUE THREAD

**Issue by N48s** [KenHuffman/UltimakerCuraScripts#1] opened 2022-11-15 05:46 UTC
Hey have been trying since yesterday to get this code to work but can’t seem to. I’ve saved link as and tried that way, I’ve copied and pasted your code and made a new py file, I’ve even tried re rewriting the old code with yours but didn’t work either, am I doing something wrong hahaha. Cheers for the effort of trying to get this working. I’m ever so keen for it haha

**Comment by KenHuffman** [comment] 2022-11-15 15:51
Things to try.
- Make sure you are running Cura 5
- Try 200x200 for the size
- If you have other plugins that modify g-code you may need to remove them. The Creality firmware is very picky about where the image is placed in the file and multiple plugins may affect that.
- Start cura with the --debug flag and see if it complains as it load the scripts.
- Look at the top of the gcode file it generates, it should contain a line that looks like:
`; jpg begin 200*200 3486 3 197 500`

**Comment by KenHuffman** [comment] 2022-11-15 15:52
@N48s Can you send me the gcode file that was generated? You can also email me your source STL to see if I can successfully generate a preview from it. Can you send me the cura.log file?

**Comment by KenHuffman** [comment] 2022-11-18 01:14
Since you reported a bug, I’m hoping to reach you to resolve the issue.Can you read my response and get back with me?On Nov 15, 2022, at 12:46 AM, N48s ***@***.***> wrote:﻿
Hey have been trying since yesterday to get this code to work but can’t seem to. I’ve saved link as and tried that way, I’ve copied and pasted your code and made a new py file, I’ve even tried re rewriting the old code with yours but didn’t work either, am I doing something wrong hahaha. Cheers for the effort of trying to get this working. I’m ever so keen for it haha

**Comment by KenHuffman** [comment] 2022-11-28 00:37
Without any feedback from the submitter or any way to reach them, this issue will be closed as unreproducible.

**Closed as not planned by KenHuffman** 2022-11-28 00:37 UTC

**Comment by KenHuffman** [comment] 2023-01-08 14:53
@N48s Try the latest version of the script
